"use client";
import { useState } from "react";

const data={iPhone:{Pantalla:["89–189 €","45–90 min"],Batería:["59–99 €","45 min"],"Puerto de carga":["69–119 €","60–90 min"],"Otro / diagnóstico":["20–40 €","24–48 h"]},Samsung:{Pantalla:["79–179 €","45–90 min"],Batería:["49–89 €","45 min"],"Puerto de carga":["59–109 €","60–90 min"],"Otro / diagnóstico":["20–40 €","24–48 h"]},Xiaomi:{Pantalla:["69–149 €","45–90 min"],Batería:["45–79 €","45 min"],"Puerto de carga":["49–89 €","60–90 min"],"Otro / diagnóstico":["20–40 €","24–48 h"]},Otra:{Pantalla:["69–169 €","45–120 min"],Batería:["45–89 €","45–60 min"],"Puerto de carga":["49–109 €","60–90 min"],"Otro / diagnóstico":["20–40 €","24–48 h"]}};
const menu=[['Inicio','inicio'],['Reparaciones','reparaciones'],['Operadores','operadores'],['Calculadora','presupuesto'],['Contacto','contacto']];
const services=[['▣','Pantallas','Pantallas rotas, táctil que no responde y problemas de visualización.'],['ϟ','Baterías','Recupera la autonomía de tu dispositivo.'],['↯','Conectores','Puerto de carga, cámaras, altavoz y botones.'],['⌕','Diagnóstico','Daños por agua y averías que requieren revisión.']];
const operators=['lowi','Lebara','llamaya','simyo','amena','República Móvil','Orange Mundo'];

export default function Home(){
 const [open,setOpen]=useState(false),[brand,setBrand]=useState(''),[issue,setIssue]=useState(''),[repair,setRepair]=useState(''),[sent,setSent]=useState(false); const quote=brand&&issue?data[brand][issue]:null;
 const reserve=()=>{setRepair(`${issue} · ${brand} (${quote[0]})`);document.getElementById('contacto').scrollIntoView({behavior:'smooth'})};
 return <><header><nav className="container nav"><a className="brand" href="#inicio"><b>W</b>World <i>phone</i></a><div className="links">{menu.map(([x,id])=><a key={id} href={`#${id}`}>{x}</a>)}</div><a className="btn dark" href="#contacto">Pedir cita</a><button className="hamb" onClick={()=>setOpen(!open)}>☰</button></nav>{open&&<div className="mobile">{menu.map(([x,id])=><a onClick={()=>setOpen(false)} key={id} href={`#${id}`}>{x}</a>)}</div>}</header>
 <main><section id="inicio" className="hero"><div className="container two"><div><p className="eyebrow">● REPARACIÓN RÁPIDA · PAMPLONA</p><h1>Tu móvil vuelve a estar <em>como nuevo.</em></h1><p className="lead">Reparamos smartphones con rapidez y claridad. También te ayudamos a contratar móvil, fibra y tarifas con los principales operadores.</p><p className="actions"><a className="btn blue" href="#presupuesto">Calcular presupuesto</a><a className="btn white" href="#contacto">Pedir cita</a></p><div className="stats"><span><b>45 min</b>reparaciones comunes</span><span><b>7 marcas</b>operadoras disponibles</span><span><b>1 tienda</b>en Pamplona</span></div></div><div className="phone"><div><small>WORLD PHONE　　　　　 09:41</small><article><small>Tu reparación</small><b>Lista hoy</b><hr /></article><article className="white-card"><small>PANTALLA · IPHONE 13</small><b>Recogida a las 12:30</b></article></div></div></div></section>
 <section id="reparaciones" className="container section"><p className="eyebrow blue-text">REPARACIONES QUE SOLUCIONAN</p><h2>Tu dispositivo en buenas manos.</h2><p className="intro">Revisamos el problema, te explicamos la solución y confirmamos el precio antes de empezar.</p><div className="cards">{services.map(([icon,title,text])=><article key={title}><span>{icon}</span><h3>{title}</h3><p>{text}</p></article>)}</div><div className="accessories"><span><b>También tenemos accesorios.</b> Fundas, cargadores, protectores, cables, auriculares y más.</span><a href="#contacto">Consultar disponibilidad →</a></div></section>
 <section id="operadores" className="operators"><div className="container"><div className="operator-intro"><div><p className="eyebrow lime">TELEFONÍA Y CONECTIVIDAD</p><h2>Tu tarifa, explicada sin letra pequeña.</h2></div><p>Compara con nosotros opciones de móvil, fibra y llamadas. Te ayudamos a encontrar la tarifa que encaja contigo.</p></div><div className="operator-grid">{operators.map(x=><b key={x} className={x.toLowerCase().replaceAll(' ','-')}>{x}</b>)}</div><small>Las marcas mostradas pertenecen a sus respectivos titulares. Consulta en tienda la disponibilidad y las condiciones vigentes.</small></div></section>
 <section id="presupuesto" className="estimate"><div className="container"><div className="center"><p className="eyebrow blue-text">EN MENOS DE UN MINUTO</p><h2>Calcula tu presupuesto orientativo.</h2><p>Confirmaremos el precio exacto tras revisar el dispositivo.</p></div><div className="calculator"><div className="controls"><p>01 · CUÉNTANOS QUÉ NECESITAS</p><label>Marca o dispositivo<select value={brand} onChange={e=>setBrand(e.target.value)}><option value="">Selecciona una marca</option>{Object.keys(data).map(x=><option key={x}>{x}</option>)}</select></label><label>¿Qué problema tiene?<select value={issue} onChange={e=>setIssue(e.target.value)}><option value="">Selecciona una reparación</option>{['Pantalla','Batería','Puerto de carga','Otro / diagnóstico'].map(x=><option key={x}>{x}</option>)}</select></label></div><aside><p className="eyebrow lime">02 · TU ESTIMACIÓN</p><h3>{quote?`${issue} · ${brand}`:'Selecciona una reparación'}</h3><p>{quote?'Precio orientativo. Revisaremos el modelo y su estado antes de confirmarlo.':'Verás un rango de precio y el tiempo habitual de reparación.'}</p><strong>{quote?.[0]||'—'}</strong><small>Tiempo estimado: {quote?.[1]||'—'}</small><button disabled={!quote} className="btn lime-btn" onClick={reserve}>Reservar con este presupuesto</button></aside></div></div></section>
 <section id="contacto" className="container contact"><div><p className="eyebrow blue-text">VISÍTANOS O RESERVA</p><h2>Estamos cerca de ti.</h2><div className="details"><p><b>⌖　Tienda</b><a target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query=C.+de+Francisco+Bergamin+Kalea,+31,+31003+Pamplona">C. de Francisco Bergamin Kalea, 31<br />31003 Pamplona, Navarra</a></p><p><b>◷　Horario</b>Lunes a viernes: 10:00–14:00 · 17:00–20:00<br />Sábado: 10:00–14:00 · Domingo: cerrado</p></div><a className="btn white" target="_blank" rel="noreferrer" href="https://www.google.com/maps/search/?api=1&query=C.+de+Francisco+Bergamin+Kalea,+31,+31003+Pamplona">Cómo llegar en Google Maps →</a></div><form onSubmit={e=>{e.preventDefault();setSent(true)}}><h3>Pide tu cita</h3><p>Te responderemos para confirmar la disponibilidad.</p><div className="formgrid"><Input label="Nombre"/><Input label="Teléfono" type="tel"/></div><label>Reparación o consulta<input required value={repair} onChange={e=>setRepair(e.target.value)} placeholder="Ej. Cambio de pantalla iPhone"/></label><label>Mensaje <small>(opcional)</small><textarea rows="4" placeholder="Modelo del móvil, disponibilidad, dudas…"/></label><button className="btn blue full">Solicitar cita</button>{sent&&<p className="success">¡Solicitud preparada! Conecta este formulario a tu correo o WhatsApp para recibir reservas reales.</p>}</form></section></main>
 <footer><div className="container footer"><div><b>World <i>phone</i></b><p>Reparación de móviles y telecomunicaciones en Pamplona.</p></div><div><b>Enlaces</b><a href="#reparaciones">Reparaciones</a><a href="#operadores">Operadores</a><a href="#presupuesto">Presupuestos</a></div><div><b>Contacto</b><p>C. de Francisco Bergamin Kalea, 31<br/>31003 Pamplona, Navarra</p></div></div><small>© {new Date().getFullYear()} World phone. Todos los derechos reservados · Aviso legal · Política de privacidad</small></footer></>
}
function Input({label,type='text'}){return <label>{label}<input required type={type} placeholder={`Tu ${label.toLowerCase()}`}/></label>}
